#!/bin/sh
#
# slideslope -- Downloads slides (in .swf format) from slideshare.net
#
# Copyright © 2012 Samuel Lidén Borell <samuel@slbdata.se>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

docid=`wget -q -O- "$1" | grep -oE 'doc=[a-z0-9A-Z-]+' | head -n 1 | sed s/^doc=//`

echo "DOCID=>$docid<"
if [ -z "$docid" ]; then
    echo "Could not find docid in HTML source code!">&2
    exit 1
fi

wget -- `wget -O- "https://s3.amazonaws.com/slideshare/$docid.xml" | grep -oE '"http://[^"]*"' | sed 's/"//g' | while read url; do
    echo "$url"
done`


