#!/bin/sh
#
# swfs2png -- Renders .swf files in a directory to .png using Gnash
#
# Copyright © 2012 Samuel Lidén Borell <samuel@slbdata.se>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

if [ -z "$1" ]; then
    echo "usage: $0 common-prefix-of-swf-files" >&2
    exit 2
fi

prefix() {
    case ${#1} in
        1) echo 0000$1;;
        2) echo 000$1;;
        3) echo 00$1;;
        4) echo 0$1;;
        *) echo $1;;
    esac
}

for file in "$1"*; do
    end=${file##$1}
    counter=${end%%.swf}
    gnash --once --screenshot last --screenshot-file slide-`prefix $counter`.png "$file"
    #echo -- gnash --once --screenshot last --screenshot-file slide-`prefix $counter`.png "$file"
done


